### ISSUE TITLE
.??

### ISSUE THREAD

**Issue by schwie** [EricFromCanada/ericfromcanada.github.io#2]
@EricFromCanada, this isn't so much an issue as its a "thank you!" for posting these instructions. What a generous gift to the macOS Server community.

I was hoping to combine your approach with wildcard certificates as discussed here:

[https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7](https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7)
and
[https://marcincuber.medium.com/lets-encrypt-generating-wildcard-ssl-certificate-using-certbot-ae1c9484c101](https://marcincuber.medium.com/lets-encrypt-generating-wildcard-ssl-certificate-using-certbot-ae1c9484c101)

I think I solved it in section "Creating the certificate" by changing this line:

sudo certbot certonly --standalone -d server.internal.company.ca

to:

sudo certbot certonly --manual --preferred-challenges=dns --email admin@company.ca --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.company.ca

When --preferred-challenges=dns is used, I had to create a TXT record with my registrar, but after you do this once you shouldn't have to do it again and I'm hoping further renewals with your script go as planned. I'll report back when I know they are working.

**Comment by EricFromCanada** [comment]
Thanks for the kind words. (I didn't cover wildcard certificates in the post because it wasn't applicable in my situation, and I wanted the post to focus on teaching instead of covering multiple use cases).

The difficulty with wildcard certificates is that for each renewal, they require a new value to be set for their TXT record. Given that you don't want to be manually running that command and updating said value every three months, you'll want Certbot to update it for you, and the method used would vary depending on where your DNS is hosted. This forum post lists which [DNS providers offer integration](https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438) of some sort for this, either via a Certbot plugin or via other means. This blog post goes through [using one of these plugins](https://developerinsider.co/how-to-create-and-auto-renew-lets-encrypt-wildcard-certificate/) to automate wildcard certificate renewals.

**Comment by schwie** [comment]
Super helpful - thanks for responding and posting these links!

ZoneEdit is the DNS provider I use and they don't yet have an API supporting certbot. I may have to re-think wildcards and if I really need to use one – a redirect within Server.app's Websites pane may be a better approach and maybe this is what you use?

**Comment by EricFromCanada** [comment]
I found [this script](https://github.com/jeansergegagnon/zoneedit_letsencrypt) which is intended for Linux, but might work on macOS with a bit of modification (e.g. it only looks for `certbot-auto`, so you'd want to add a symlink from `/usr/local/bin/certbot-auto` to `/usr/local/bin/certbot`).

**Comment by schwie** [comment]
@EricFromCanada, just to follow up on this string and for others who come into this... Earlier this year, I was migrating one of my servers and potentially needing the script you linked to above, but I ended up rolling with Bernard Teo's [Webmon](http://cutedgesystems.com/software/WebMonforMonterey/), which has an option to automatically renew certificates. With Webmon running the show and renewing letsencrypt certificates, my server suddenly has no more need for the above script. Anyway, thanks again for your past responses.
